feat: try append k8s

diff --git a/.github/workflows/kubernetes.yml b/.github/workflows/kubernetes.yml
--- a/.github/workflows/kubernetes.yml
+++ b/.github/workflows/kubernetes.yml
@@ -109,135 +109,122 @@ jobs:
           subject-name: ${{ env.REGISTRY }}/${{ env.SERVER_IMAGE_NAME}}
           subject-digest: ${{ steps.push.outputs.digest }}
           push-to-registry: true
-#
-#  deploy:
-#    environment: kubernetes
-#    needs:
-#      [
-#        release,
-#        check-server-image,
-#        build-and-push-migrations-image,
-#        build-and-push-server-image,
-#        build-and-push-nginx-image,
-#        build-and-push-e2e-tests-image,
-#      ]
-#    runs-on: [self-hosted]
-#    env:
-#      ROOT_VERSION: ${{ needs.release.outputs.root_version }}
-#      SERVER_VERSION: ${{ needs.release.outputs.server_version }}
-#      CLIENT_VERSION: ${{ needs.release.outputs.client_version }}
-#
-#    steps:
-#      - name: Checkout repository
-#        uses: actions/checkout@v4
-#        with:
-#          # We must fetch at least the immediate parents so that if this is
-#          # a pull request then we can checkout the head.
-#          fetch-depth: 2
-#
-#      - name: Deploy infrastructure
-#        if: ${{ needs.check-server-image.outputs.result != 'success' || contains(github.event.head_commit.message, '[skip cache]') || contains(github.event.head_commit.message, '[skip infrastructure]') }}
-#        env:
-#          SERVER_APP_DATABASE_NAME: ${{ secrets.SERVER_APP_DATABASE_NAME }}
-#          SERVER_APP_DATABASE_PASSWORD: ${{ secrets.SERVER_APP_DATABASE_PASSWORD }}
-#          SERVER_APP_DATABASE_USERNAME: ${{ secrets.SERVER_APP_DATABASE_USERNAME }}
-#          SERVER_POSTGRE_SQL_POSTGRESQL_DATABASE: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_DATABASE }}
-#          SERVER_POSTGRE_SQL_POSTGRESQL_PASSWORD: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_PASSWORD }}
-#          SERVER_POSTGRE_SQL_POSTGRESQL_USERNAME: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_USERNAME }}
-#          SERVER_WEBHOOK_DATABASE_NAME: ${{ secrets.SERVER_WEBHOOK_DATABASE_NAME }}
-#          SERVER_WEBHOOK_DATABASE_PASSWORD: ${{ secrets.SERVER_WEBHOOK_DATABASE_PASSWORD }}
-#          SERVER_WEBHOOK_DATABASE_USERNAME: ${{ secrets.SERVER_WEBHOOK_DATABASE_USERNAME }}
-#          SERVER_AUTH_DATABASE_NAME: ${{ secrets.SERVER_AUTH_DATABASE_NAME }}
-#          SERVER_AUTH_DATABASE_PASSWORD: ${{ secrets.SERVER_AUTH_DATABASE_PASSWORD }}
-#          SERVER_AUTH_DATABASE_USERNAME: ${{ secrets.SERVER_AUTH_DATABASE_USERNAME }}
-#          SERVER_AUTHORIZER_ADMIN_SECRET: ${{ secrets.SERVER_AUTHORIZER_ADMIN_SECRET }}
-#          SERVER_AUTH_ADMIN_PASSWORD: ${{ secrets.SERVER_AUTH_ADMIN_PASSWORD }}
-#          SERVER_MINIO_MINIO_ROOT_USER: ${{ secrets.SERVER_MINIO_MINIO_ROOT_USER }}
-#          SERVER_MINIO_MINIO_ROOT_PASSWORD: ${{ secrets.SERVER_MINIO_MINIO_ROOT_PASSWORD }}
-#          SERVER_REDIS_REDIS_PASSWORD: ${{ secrets.SERVER_REDIS_REDIS_PASSWORD }}
-#        run: |
-#          rm -rf ./.kubernetes/generated
-#          . .kubernetes/set-env.sh && npx -y rucken copy-paste --find=templates --replace=generated --replace-plural=generated --path=./.kubernetes/templates --replace-envs=true
-#          docker compose -f ./.kubernetes/generated/docker-compose-infra.yml --compatibility down || echo 'docker-compose-infra not started'
-#          docker compose -f ./.kubernetes/generated/docker-compose-infra.yml --compatibility up -d
-#
-#      - name: Deploy applications
-#        # if: ${{ needs.check-server-image.outputs.result != 'success' || contains(github.event.head_commit.message, '[skip cache]') || contains(github.event.head_commit.message, '[skip applications]') }}
-#        env:
-#          DOCKER_SERVER: ${{ env.REGISTRY }}
-#          DOCKER_USERNAME: ${{ github.actor }}
-#          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
-#          SERVER_DOMAIN: ${{ secrets.SERVER_DOMAIN }}
-#          SERVER_APP_DATABASE_NAME: ${{ secrets.SERVER_APP_DATABASE_NAME }}
-#          SERVER_APP_DATABASE_PASSWORD: ${{ secrets.SERVER_APP_DATABASE_PASSWORD }}
-#          SERVER_APP_DATABASE_USERNAME: ${{ secrets.SERVER_APP_DATABASE_USERNAME }}
-#          SERVER_POSTGRE_SQL_POSTGRESQL_DATABASE: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_DATABASE }}
-#          SERVER_POSTGRE_SQL_POSTGRESQL_PASSWORD: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_PASSWORD }}
-#          SERVER_POSTGRE_SQL_POSTGRESQL_USERNAME: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_USERNAME }}
-#          SERVER_WEBHOOK_DATABASE_NAME: ${{ secrets.SERVER_WEBHOOK_DATABASE_NAME }}
-#          SERVER_WEBHOOK_DATABASE_PASSWORD: ${{ secrets.SERVER_WEBHOOK_DATABASE_PASSWORD }}
-#          SERVER_WEBHOOK_DATABASE_USERNAME: ${{ secrets.SERVER_WEBHOOK_DATABASE_USERNAME }}
-#          SERVER_AUTH_DATABASE_NAME: ${{ secrets.SERVER_AUTH_DATABASE_NAME }}
-#          SERVER_AUTH_DATABASE_PASSWORD: ${{ secrets.SERVER_AUTH_DATABASE_PASSWORD }}
-#          SERVER_AUTH_DATABASE_USERNAME: ${{ secrets.SERVER_AUTH_DATABASE_USERNAME }}
-#          SERVER_AUTHORIZER_ADMIN_SECRET: ${{ secrets.SERVER_AUTHORIZER_ADMIN_SECRET }}
-#          SERVER_AUTH_ADMIN_PASSWORD: ${{ secrets.SERVER_AUTH_ADMIN_PASSWORD }}
-#          SERVER_MINIO_MINIO_ROOT_USER: ${{ secrets.SERVER_MINIO_MINIO_ROOT_USER }}
-#          SERVER_MINIO_MINIO_ROOT_PASSWORD: ${{ secrets.SERVER_MINIO_MINIO_ROOT_PASSWORD }}
-#          SERVER_REDIS_REDIS_PASSWORD: ${{ secrets.SERVER_REDIS_REDIS_PASSWORD }}
-#        # since the server is very slow, it may freeze, and therefore you have to restart MicroK8s
-#        run: |
-#          echo 'Start'
-#          rm -rf ./.kubernetes/generated
-#          . .kubernetes/set-env.sh && npx -y rucken copy-paste --find=templates --replace=generated --replace-plural=generated --path=./.kubernetes/templates --replace-envs=true
-#          echo 'Check k8s'
-#          sudo microk8s status --wait-ready | echo 'Skip error'
-#          echo 'Stop k8s'
-#          sudo microk8s stop
-#          sudo microk8s status --wait-ready | echo 'Skip error'
-#          echo 'Start k8s'
-#          sudo microk8s start
-#          sudo microk8s status --wait-ready | echo 'Skip error'
-#          echo 'Start apply k8s'
-#          chmod +x .kubernetes/generated/install.sh
-#          .kubernetes/generated/install.sh > /dev/null 2>&1
-#          echo 'End'
-#
-#  e2e-tests:
-#    environment: kubernetes
-#    runs-on: ubuntu-latest
-#    needs: [release, deploy]
-#    permissions:
-#      contents: read
-#      packages: read
-#      id-token: write
-#    env:
-#      ROOT_VERSION: ${{ needs.release.outputs.root_version }}
-#      SERVER_VERSION: ${{ needs.release.outputs.server_version }}
-#      CLIENT_VERSION: ${{ needs.release.outputs.client_version }}
-#    steps:
-#      - name: Checkout repository
-#        if: ${{ !contains(github.event.head_commit.message, '[skip e2e]') }}
-#        uses: actions/checkout@v4
-#      - name: Log in to the Container registry
-#        if: ${{ !contains(github.event.head_commit.message, '[skip e2e]') }}
-#        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
-#        with:
-#          registry: ${{ env.REGISTRY }}
-#          username: ${{ github.actor }}
-#          password: ${{ secrets.GITHUB_TOKEN }}
-#      - name: Run E2E-tests
-#        if: ${{ !contains(github.event.head_commit.message, '[skip e2e]') }}
-#        env:
-#          SERVER_DOMAIN: ${{ secrets.SERVER_DOMAIN }}
-#          SERVER_AUTH_ADMIN_PASSWORD: ${{ secrets.SERVER_AUTH_ADMIN_PASSWORD }}
-#          SERVER_AUTHORIZER_ADMIN_SECRET: ${{ secrets.SERVER_AUTHORIZER_ADMIN_SECRET }}
-#        run: |
-#          rm -rf ./.kubernetes/generated
-#          . .kubernetes/set-env.sh && npx -y rucken copy-paste --find=templates --replace=generated --replace-plural=generated --path=./.kubernetes/templates --replace-envs=true
-#          npx -y wait-on --log https://$SERVER_DOMAIN/api/health --log https://$SERVER_DOMAIN
-#          docker compose -f ./.kubernetes/generated/docker-compose-e2e-tests.yml --compatibility up
-#      - uses: actions/upload-artifact@v4
-#        with:
-#          name: e2e-tests-videos
-#          path: apps/client-e2e/src/video/
+
+  deploy:
+    environment: kubernetes
+    needs: [release, check-server-image, build-and-push-server-image]
+    runs-on: [self-hosted]
+    env:
+      ROOT_VERSION: ${{ needs.release.outputs.root_version }}
+      SERVER_VERSION: ${{ needs.release.outputs.server_version }}
+      CLIENT_VERSION: ${{ needs.release.outputs.client_version }}
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          # We must fetch at least the immediate parents so that if this is
+          # a pull request then we can checkout the head.
+          fetch-depth: 2
+
+      - name: Deploy infrastructure
+        if: ${{ needs.check-server-image.outputs.result != 'success' || contains(github.event.head_commit.message, '[skip cache]') || contains(github.event.head_commit.message, '[skip infrastructure]') }}
+        env:
+          SERVER_POSTGRE_SQL_POSTGRESQL_DATABASE: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_DATABASE }}
+          SERVER_POSTGRE_SQL_POSTGRESQL_PASSWORD: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_PASSWORD }}
+          SERVER_POSTGRE_SQL_POSTGRESQL_USERNAME: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_USERNAME }}
+          SERVER_WEBHOOK_DATABASE_NAME: ${{ secrets.SERVER_WEBHOOK_DATABASE_NAME }}
+          SERVER_WEBHOOK_DATABASE_PASSWORD: ${{ secrets.SERVER_WEBHOOK_DATABASE_PASSWORD }}
+          SERVER_WEBHOOK_DATABASE_USERNAME: ${{ secrets.SERVER_WEBHOOK_DATABASE_USERNAME }}
+          SERVER_SSO_DATABASE_NAME: ${{ secrets.SERVER_SSO_DATABASE_NAME }}
+          SERVER_SSO_DATABASE_PASSWORD: ${{ secrets.SERVER_SSO_DATABASE_PASSWORD }}
+          SERVER_SSO_DATABASE_USERNAME: ${{ secrets.SERVER_SSO_DATABASE_USERNAME }}
+          SERVER_SSO_ADMIN_PASSWORD: ${{ secrets.SERVER_SSO_ADMIN_PASSWORD }}
+          SERVER_MINIO_MINIO_ROOT_USER: ${{ secrets.SERVER_MINIO_MINIO_ROOT_USER }}
+          SERVER_MINIO_MINIO_ROOT_PASSWORD: ${{ secrets.SERVER_MINIO_MINIO_ROOT_PASSWORD }}
+          SERVER_REDIS_REDIS_PASSWORD: ${{ secrets.SERVER_REDIS_REDIS_PASSWORD }}
+        run: |
+          rm -rf ./.kubernetes/generated
+          . .kubernetes/set-env.sh && npx -y rucken copy-paste --find=templates --replace=generated --replace-plural=generated --path=./.kubernetes/templates --replace-envs=true
+          docker compose -f ./.kubernetes/generated/docker-compose-infra.yml --compatibility down || echo 'docker-compose-infra not started'
+          docker compose -f ./.kubernetes/generated/docker-compose-infra.yml --compatibility up -d
+
+      - name: Deploy applications
+        if: ${{ needs.check-server-image.outputs.result != 'success' || contains(github.event.head_commit.message, '[skip cache]') || contains(github.event.head_commit.message, '[skip applications]') }}
+        env:
+          DOCKER_SERVER: ${{ env.REGISTRY }}
+          DOCKER_USERNAME: ${{ github.actor }}
+          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
+          SERVER_DOMAIN: ${{ secrets.SERVER_DOMAIN }}
+          SERVER_POSTGRE_SQL_POSTGRESQL_DATABASE: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_DATABASE }}
+          SERVER_POSTGRE_SQL_POSTGRESQL_PASSWORD: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_PASSWORD }}
+          SERVER_POSTGRE_SQL_POSTGRESQL_USERNAME: ${{ secrets.SERVER_POSTGRE_SQL_POSTGRESQL_USERNAME }}
+          SERVER_WEBHOOK_DATABASE_NAME: ${{ secrets.SERVER_WEBHOOK_DATABASE_NAME }}
+          SERVER_WEBHOOK_DATABASE_PASSWORD: ${{ secrets.SERVER_WEBHOOK_DATABASE_PASSWORD }}
+          SERVER_WEBHOOK_DATABASE_USERNAME: ${{ secrets.SERVER_WEBHOOK_DATABASE_USERNAME }}
+          SERVER_SSO_DATABASE_NAME: ${{ secrets.SERVER_SSO_DATABASE_NAME }}
+          SERVER_SSO_DATABASE_PASSWORD: ${{ secrets.SERVER_SSO_DATABASE_PASSWORD }}
+          SERVER_SSO_DATABASE_USERNAME: ${{ secrets.SERVER_SSO_DATABASE_USERNAME }}
+          SERVER_SSO_ADMIN_PASSWORD: ${{ secrets.SERVER_SSO_ADMIN_PASSWORD }}
+          SERVER_MINIO_MINIO_ROOT_USER: ${{ secrets.SERVER_MINIO_MINIO_ROOT_USER }}
+          SERVER_MINIO_MINIO_ROOT_PASSWORD: ${{ secrets.SERVER_MINIO_MINIO_ROOT_PASSWORD }}
+          SERVER_REDIS_REDIS_PASSWORD: ${{ secrets.SERVER_REDIS_REDIS_PASSWORD }}
+          SERVER_SSO_CLIENT_URL: ${{ secrets.SERVER_SSO_CLIENT_URL }}
+          SERVER_SSO_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.SERVER_SSO_GOOGLE_OAUTH_CLIENT_ID }}
+          SERVER_SSO_GOOGLE_OAUTH_CLIENT_SECRET_KEY: ${{ secrets.SERVER_SSO_GOOGLE_OAUTH_CLIENT_SECRET_KEY }}
+          SERVER_SSO_ADMIN_SECRET: ${{ secrets.SERVER_SSO_ADMIN_SECRET }}
+        # since the server is very slow, it may freeze, and therefore you have to restart MicroK8s
+        run: |
+          echo 'Start'
+          rm -rf ./.kubernetes/generated
+          . .kubernetes/set-env.sh && npx -y rucken copy-paste --find=templates --replace=generated --replace-plural=generated --path=./.kubernetes/templates --replace-envs=true
+          echo 'Check k8s'
+          sudo microk8s status --wait-ready | echo 'Skip error'
+          echo 'Stop k8s'
+          sudo microk8s stop
+          sudo microk8s status --wait-ready | echo 'Skip error'
+          echo 'Start k8s'
+          sudo microk8s start
+          sudo microk8s status --wait-ready | echo 'Skip error'
+          echo 'Start apply k8s'
+          chmod +x .kubernetes/generated/install.sh
+          .kubernetes/generated/install.sh > /dev/null 2>&1
+          echo 'End'
+
+  # e2e-tests:
+  #   environment: kubernetes
+  #   runs-on: ubuntu-latest
+  #   needs: [release, deploy]
+  #   permissions:
+  #     contents: read
+  #     packages: read
+  #     id-token: write
+  #   env:
+  #     ROOT_VERSION: ${{ needs.release.outputs.root_version }}
+  #     SERVER_VERSION: ${{ needs.release.outputs.server_version }}
+  #     CLIENT_VERSION: ${{ needs.release.outputs.client_version }}
+  #   steps:
+  #     - name: Checkout repository
+  #       if: ${{ !contains(github.event.head_commit.message, '[skip e2e]') }}
+  #       uses: actions/checkout@v4
+  #     - name: Log in to the Container registry
+  #       if: ${{ !contains(github.event.head_commit.message, '[skip e2e]') }}
+  #       uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
+  #       with:
+  #         registry: ${{ env.REGISTRY }}
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Run E2E-tests
+  #       if: ${{ !contains(github.event.head_commit.message, '[skip e2e]') }}
+  #       env:
+  #         SERVER_DOMAIN: ${{ secrets.SERVER_DOMAIN }}
+  #         SERVER_SSO_ADMIN_PASSWORD: ${{ secrets.SERVER_SSO_ADMIN_PASSWORD }}
+  #       run: |
+  #         rm -rf ./.kubernetes/generated
+  #         . .kubernetes/set-env.sh && npx -y rucken copy-paste --find=templates --replace=generated --replace-plural=generated --path=./.kubernetes/templates --replace-envs=true
+  #         npx -y wait-on --log https://$SERVER_DOMAIN/api/health --log https://$SERVER_DOMAIN
+  #         docker compose -f ./.kubernetes/generated/docker-compose-e2e-tests.yml --compatibility up
+  #     - uses: actions/upload-artifact@v4
+  #       with:
+  #         name: e2e-tests-videos
+  #         path: apps/client-e2e/src/video/
